version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/rupeshkunwar/test-app/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
           docker build -t rupesh1050/react-test -f ./client/Dockerfile.dev ./client
          

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name