version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: build image
          command: |
            sudo usermod -aG docker $USER
            docker build -t rupesh1050/react-test -f ./client/Dockerfile.dev ./client
  unit-test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Run unit unit
          command: docker run -e CI=true rupesh1050/react-test npm test
  publish-to-docker-hub:
    docker:
      - image: cimg/base:stable
    steps:
      - run: docker login -u "${DOCKER_HUB_USER}" -p "${DOCKER_HUB_PASSWORD}"
      - run:
          name: docker build
          command: |
                docker build -t rupesh1050/multi-client:latest ./client
                docker build -t rupesh1050/multi-nginx:latest ./nginx
                docker build -t rupesh1050/multi-server:latest ./server
                docker build -t rupesh1050/multi-worker:latest ./worker
      - run:
          name: Tag and push to docker hub
          command: |
                  docker push rupesh1050/multi-client
                  docker push rupesh1050/multi-nginx
                  docker push rupesh1050/multi-server
                  docker push rupesh1050/multi-worker

workflows:
  build_and_deploy:
    jobs:
      - build
      - unit-test:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
                - main
      - publish-to-docker-hub:
          requires:
            - unit-test
          filters:
            branches:
              only:
                - dev
                - main
