name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
  DeployDev:
    name: Deploy to Dev 
    if: |
     github.event.ref == 'refs/heads/main' 
    needs: [build ]
    runs-on: ubuntu-latest
    environment: 
      name: Dev
      url: 'https://www.accern.com'
    steps:
      - name: Build and publish
        run: echo I am deploying on Dev Environment ! 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Build the container image
        run: | 
            docker build . --file ./client/Dockerfile --tag rupesh1050/multi-client:latest
            docker build . --file ./nginx/Dockerfile --tag rupesh1050/multi-nginx:latest
            docker build . --file ./server/Dockerfile --tag rupesh1050/multi-server:latest
            docker build . --file ./worker/Dockerfile --tag rupesh1050/multi-worker:latest
      - uses: anchore/scan-action@v3
        with:
            image: |
                 "rupesh1050/multi-client:latest"
                 "rupesh1050/multi-nginx:latest"
                 "rupesh1050/multi-server:latest"
                 "rupesh1050/multi-worker:latest"
            fail-build: ture
      - uses: actions/checkout@master
      - name: Publish to rupesh1050/multi-client
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rupesh1050/multi-client
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile

      - name: Publish to rupesh1050/multi-nginx
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rupesh1050/multi-nginx
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tag_with_ref: 'refs/*'
          labels: ${{ steps.meta.outputs.labels }}
      - name: Publish to rupesh1050/multi-server
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rupesh1050/multi-server
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tag_with_ref: 'refs/*'
          labels: ${{ steps.meta.outputs.labels }}
      - name: Publish to rupesh1050/multi-worker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rupesh1050/multi-worker
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tag_with_ref: 'refs/*'
          labels: ${{ steps.meta.outputs.labels }}