name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    
  DeployDev:
    name: Deploy to Dev 
    if: |
     github.event.ref == 'refs/heads/main' 
    needs: [build ]
    runs-on: ubuntu-latest
    environment: 
      name: Dev
      url: 'https://www.accern.com'
    steps:
      - name: Build and publish
        run: echo I am deploying on Dev Environment ! 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Build the container image
        run: | 
            docker build -t rupesh1050/multi-client:latest ./client
      - uses: anchore/scan-action@v3
        with:
            image: "rupesh1050/multi-client:latest"
            fail-build: false
      - uses: actions/checkout@master
      - name: Publish to rupesh1050/multi-client
        run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin
            docker push rupesh1050/multi-client
