name: test-app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    

  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http:${{ env.PUBLIC_IP }}'
    steps:
      - name: Deploy
        run: echo I am deploying! 
      - uses: actions/checkout@v2
      - name: Set up Digitalocean cluster
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: ${{secrets.CLUSTER_NAME}}

      - name: create secret
        run: |
          kubectl create namespace ${{ github.event.repository.name }}
          kubectl create secret generic pgpassword --from-literal PGPASSWORD=${{ secrets.PGPASSWORD}} -n ${{ github.event.repository.name }}
           
      - name : deploy on cluster 
        run : kubectl apply -f ./k8s -n ${{ github.event.repository.name }}
      - name: Ingress Ip
        id: ipv4
        run: |
          echo 'PUBLIC_IP<<EOF' >> $GITHUB_ENV
          kubectl get svc -n ingress-nginx | grep LoadBalancer | awk '{ print $4 }' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV